project:
  type: website
  render:
    - index.qmd
    - research.qmd
    - publications.qmd
    - talks.qmd
    # - cv.qmd
    - misc.qmd
    - links.qmd

resources:
  - assets/

website:
  title: "Jun Yamamoto"
  image: assets/images/logo.png
  repo-url: "https://github.com/jym16/homepage"
  repo-actions: [issue]
  page-navigation: true
  reader-mode: true
  back-to-top-navigation: true
  google-analytics: "G-GNGTP6GYPM"
  search:
    type: overlay

  page-footer:
    left:
      - text: "Powered by Quarto"
    center:
      - text: "2026 Copyright © Jun Yamamoto"
    right:
      - icon: envelope
        href: mailto:jun.j.yamamoto@gmail.com
        aria-label: Email
      - icon: mortarboard
        href: https://scholar.google.com/citations?user=ILnN9b4AAAAJ
        aria-label: Google Scholar
      - icon: github
        href: https://github.com/jym16
        aria-label: GitHub

  navbar:
    logo: assets/images/logo.png
    collapse-below: lg
    background: light

    tools:
      - icon: envelope
        href: mailto:jun.j.yamamoto@gmail.com
      - icon: mortarboard
        href: https://scholar.google.com/citations?user=ILnN9b4AAAAJ
      - icon: github
        href: https://github.com/jym16/
  
    left:
      - file: index.qmd
        text: "Home"
      - href: research.qmd
        text: "Research"
      - href: publications.qmd
        text: "Publications"
      - href: talks.qmd
        text: "Talks"
      - href: assets/cv_jyamamoto.pdf
        text: "CV"
      - href: misc.qmd
        text: "Misc"
      - href: links.qmd
        text: "Links"

format:
  html:
    theme:
      light: cosmo
      dark: cyborg
    css: 
      - assets/css/main.scss
      - assets/css/typography.css
    toc: true
    link-external-newwindow: true
    code-copy: true
    code-fold: false
    execute: 
      enabled: false
    html-math-method: katex
    include-in-header: 
      text: |
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">
  ipynb: default
