---
layout: default
permalink: /cv
title: "Curriculum Vitae"
---

## Education

2023/09 – Present  
**PhD in Network Science**  
*Department of Network and Data Science, Central European University
(Vienna, Austria)*  
— GPA: 4.0/4.0 (as of 2026/01)  
— Supervisor: Prof. Márton Pósfai, Prof. János Kertész  
— Dissertation: *Toward a general theory for physical network dynamics* (in progress)

2022/09 – 2023/09  
**MSc in Mathematics**  
*School of Mathematical Sciences, Queen Mary University of London
(London, UK)*  
— Grade: Distinction (96/100)  
— Supervisor: Prof. Ginestra Bianconi  
— Dissertation: *Modelling higher-order network dynamics in the presence
of triadic interactions*

2017/04 – 2022/03  
**BEng in Applied Physics**  
*Department of Applied Physics, School of Engineering, Hokkaido University (Sapporo, Japan)*  
— GPA: 4.18/4.30, Nitobe College Summa Cum Laude  
— Supervisor: Prof. Kousuke Yakubo  
— Thesis: *Bifractality of fractal scale-free networks*

2019/09 – 2020/05  
**Exchange Programme**  
*Department of Physics, ETH Zurich (Zurich, Switzerland)*  
(*Terminated early due to the COVID-19 pandemic)

## Employment & Internship

2022/07 – 2022/09  
**Data Scientist**  
*DX Large Data Platform Business Group, Fujitsu Limited (Tokyo, Japan)*
- Network analysis and dynamic topic modelling of news articles

2020/07 – 2020/08  
**Summer Research Intern**  
*Japan Atomic Energy Agency (Chiba, Japan)*  
— Machine learning based acceleration of molecular dynamics simulations

2019/02 – 2019/03  
**Research Intern**  
*Okinawa Institute of Science and Technology*  
— Diffraction electron microscopy for protein nanocrystals

## Teaching

2025/09 – 2025/12  
**Scientific Python, Teaching Assistant**  
*Department of Network and Data Science, Central European University*

2025/01 – 2025/03  
**Introduction to Linear Algebra, Teaching Assistant**  
*Department of Network and Data Science, Central European University*

2022/04 – 2022/08  
**Applied Mathematics II, Teaching Assistant**  
*School of Engineering, Hokkaido University*

2022/04 – 2022/08  
**Statistical Mechanics I, Teaching Assistant**  
*School of Engineering, Hokkaido University*

2021/04 – 2022/03  
**Computational Science, Teaching Assistant**  
*Center for Mathematics and Data Sciences, Hokkaido University*

2021/04 – 2022/03  
**MDS/AI Seminar, Teaching Assistant**  
*Center for Mathematics and Data Sciences, Hokkaido University*

## Academic Services

### Review Activity

- **Nature Communications** (Since 2025).
- **Transactions of the Japanese Society for Artificial Intelligence** (Since 2025).


### Organization

- **Organizer, Physical Networks III Edition** <br>
    *International School and Conference on Network Science 2025* (Maastricht, Netherlands) <br>
    2024/12 – 2025/06.

- **Organizer, Data Stories 11th Edition** <br>
    *Department of Network and Data Science, Central European University* <br>
    2024/11 – 2025/05.

## Awards

**First-Year PhD Award**  
*Central European University*  
2025/02  
For outstanding coursework and performance during the comprehensive
exam.

**Principal’s Prize**  
*Queen Mary University of London*  
2023/11  
For outstanding academic achievements.

**Ito Foundation Scholarship Award**  
*Ito Foundation for International Education Exchange*  
2022/09 – 2023/09  
¥3,000,000 tuition + \$2,000/month stipend.

**Dean’s Award**  
*Hokkaido University*  
2022/03  
For the overall academic achievements during the undergraduate studies.

**Japan Student Service Organization Scholarship Award**  
*Japan Student Service Organization*  
2019/09 - 2020/05  
Awarded ¥80,000/month for the duration of the exchange programme.

**Lane Memorial Award**  
*Hokkaido University*  
2019/07  
For outstanding grades in English in the first and second years of
undergraudate studies.

**Nitobe Award**  
*Hokkaido University*  
2018/07  
For the academic achievements in the first year of undergraduate
studies.

**Nitobe College Incentive Award**  
*Nitobe College, Hokkaido University*  
2018/06  
For the academic achievements among Nitobe College students.

## Skills

**Languages**  
Japanese (Native), English (Fluent), German (Beginner)

**Programming**  
Python, C++, Julia, Mathematica, LaTeX, Git

## Professional Memberships

**The Physical Society of Japan**  
Since 2020/11

**Austrian Physical Society**  
Since 2024/03

## Interests

**Complex Networks**  
Physical networks, Network renormalization & scale-invariance, Laplacian dynamics, Critical phenomena on complex networks

**Statistical Physics**  
Phase transitions, Critical phenomena, Fractality & Multifractality
