---
layout: default
permalink: /projects
title: "Projects"
description: "A collection of my research projects."
bibliography:
  - _bibliography/papers.bib
  - _bibliography/reference.bib
callout-appearance: minimal
---

## Physical networks {#physical-networks}

Physical networks are networks of tangible components, in which nodes and edges are embedded in physical space and subject to constraints such as volume exclusion [[@dehmamy2018structural]]. 
Examples include biological neural networks, vascular systems, porous media, and granular materials.
Advances in imaging technologies and accelerated 3D reconstruction by ML/AI have enabled to obtain detailed three-dimensional maps of such complex systems, providing new opportunities to study general organizing principles for tangible complex systems.

While the physical layout of networks has been shown to give rise to emergent structural properties, such as entanglement [[@liu2021isotopy, @glover2024measuring]], bundling [@bonamassa2025logarithmic], jamming [@posfai2024impact], and correlations between node degree and node volume [@pete2024physical], it remains elusive how these would impact dynamical processes that unfold on physical networks.

For my PhD thesis, I am exploring the spectral and topological properties of physical networks and their dynamical implications through *physical Laplacian*, a vertex-weighted graph Laplacian for physical networks derived in [@pete2024physical] as
\begin{align}
  \mathbf{Q}_{\textrm{P}} = \mathbf{V}^{-1/2} \mathbf{Q}_{\textrm{G}} \mathbf{V}^{-1/2}
\end{align}
where $\mathbf{G_{\textrm{G}}}$ is the combinatorial graph Laplacian and $\mathbf{V}=\mathrm{diag}(v_1, \dots, v_{N})$ is the diagonal volume matrix.

::: {.callout-note title="Localization"}

Coming soon...

:::

::: {.callout-tip title="Synchronization"}

Coming soon...

:::

<!-- 
::: {.callout-important title="Magnetization"}

Coming soon...

:::

::: {.callout-warning title="Entanglement"}

Coming soon...

::: 
-->


## Higher-order networks with triadic interactions {#triadic-interactions}

Triadic interactions are higher-order, three-body interactions in which a node modulates edge between two other nodes.
Such interactions are reported in various real-world systems;
for example,  glia cells in the brain regulate synaptic connectivity between two neurons, either inhibiting or exciting synaptic signaling.
To model such interactions, we defined triadic interactions on network $G=(V,E)$ as an interaction between a node $i \in V$ and an edge $\ell \in E$ encoded by incidence matrix $\mathbf{K} \in \{-1, 0, 1\}^{|E| \times |V|}$ with entries
\begin{align}
  K_{\ell i} = \begin{cases}
    -1 & \text{if node $i$ inhibits edge $\ell$}, \\
    1 & \text{if node $i$ excites edge $\ell$}, \\
    0 & \text{otherwise}.
  \end{cases}
\end{align}
Signed triadic interactions turn percolation processes into dynamical ones, with phenomena such as a period doubling and chaos [[@sun2023dynamic], [@sun2024higher], [@millan2024triadic]], and dynamical implications of triadic interactions remain an important but open question. 

::: {.callout-note title="Langevin dynamics on networks with triadic interactions"}

To investigate how triadic interactions affect dynamics, we studied Langevin dynamics on networks incorporating triadic interactions
\begin{align}
  d\mathbf{X} = - (\mathbf{L}^{\textrm{(T)}} + \alpha \mathbf{I}) \mathbf{X} dt + \mathbf{\Gamma} d\mathbf{W}_{t}
\end{align}
where $d\mathbf{W}_{t}$ is the $|V|$-dimensional Wiener process and $\mathbf{L}^{\textrm{(T)}}$ is the triadic Laplacian 
\begin{align}
  L_{ij}^{\textrm{(T)}} (\mathbf{X}) &= \left(\sum_{k} J_{i k} (\mathbf{X}) \right) \delta_{ij} - J_{ij} (\mathbf{X})\\
  J_{ij}(\mathbf{X}; \hat{T}) &= w_{-} + (w_{+} - w_{-}) \theta\left(\sum_{k} K_{[i,j] k} X_{k} - \hat{T} \right)
\end{align}
that coevolves with $\mathbf{X}$. 
Excitation and inhibitation of triadic interactions are triggered when the states of triadically incident nodes collectively exceed a threshold $\hat{T}$.
Our results show that triadic interactions in the model are observable in conditional correlations and conditional mutual information among the three participating nodes, revealing both the strength and direction of the triadic interactions.

We applied this framework as a null model to identify potential triadic interactions in gene regulatory networks.

For details, see [@niedostatek2025mining].

:::

## Fractal scale-free networks {#fractal-scale-free-networks}

A network is *fractal* with respect to shortest-path lengths, if the minimum number of subgraphs (boxes) of diameter $l_{\textup{B}}$ required to cover the network scales as
\begin{equation}
  N_{\textup{B}}(l_{\textup{B}}) \sim l_{\textup{B}}^{-D_{\textup{f}}}
\end{equation}
where $D_{\textup{f}}$ is the fractal dimension of the network [@song2005self]. 
In fractal networks, the average path lengths also scales as the power of the network size, 
\begin{equation}
  \langle l \rangle \sim N^{1/D_{\textup{f}}}.
\end{equation}
While many empirical networks exhibit the *small-world* property, where the average path lengths scales logarithmically with the number of nodes, the fractal property can still hold at length scales shorter than the network's characteristic size. 
Detecting this scaling through shortest paths, however, is often challenging as most real networks do not have a sufficiently large diameter.

Fractal networks are of particular interest due to their well-defined structural scale invariance, which gives rise to distinctive features such as long-range degree correlations manifested as *hub repulsion* [@rozenfeld2008fractal].
Fractal network models therefore provide a natural analytical framework for studying network coarse-graining and renormalization.

::: {.callout-note title="Bifractality"}

When scale-free and fractal properties coexist, a broad class of networks exhibits *bifractality*, characterized by two distinct local fractal dimensions, $d_{\textup{f}}^{\min}$ and $d_{\textup{f}}^{\max}$ that depend on position within the network [@yamamoto2023bifractality].
In particular, consider a fractal scale-free network in which, under renormalization, the number of nodes $\nu_{\textup{B}}$ in a supernode (subgraph) of diameter $l_{\textup{B}}$ is proportional to the degree $k_{\textup{B}}$ of that supernode (i.e., the number of adjacent subgraphs):
\begin{equation}
  \nu_{\textup{B}} \propto k_{\textup{B}}.
\end{equation}
Under this condition, the network exhibits two local fractal dimensions (equivalently, Hölder exponents):
\begin{equation}
    d_{\textup{f}}^{\max} = D_{\textup{f}}, \quad d_{\textup{f}}^{\min} = D_{\textup{f}} \left(\frac{\gamma-2}{\gamma-1}\right),
\end{equation}
where $\gamma$ is the exponent of the degree distribution and $D_{\textup{f}}$ is the global fractal dimension of the network.

Extensive analytical and numerical calculations for both deterministic and stochastic models suggest that this proportionality condition holds broadly across fractal scale-free networks. 
We therefore conjecture that bifractality is a general property of fractal scale-free networks.

For details, see [@yamamoto2023bifractality].

:::

::: {.callout-tip title="Random walks on bifractal networks"}

Building on the bifractality conjecture, we studied the walk and spectral dimensions of random walks on fractal scale-free networks. 
We found that the walk dimension $d_{\textup{w}}$, which characterizes how the mean topological displacement of random walkers scales, remains constant across the network and does not depend on position.

In contrast, the spectral dimension, which governs the scaling of the return probability of a random walker, splits into two distinct values, $d_{\textup{s}}^{\min}$ and $d_{\textup{s}}^{\max}$. 
This positional dependence arises directly from the network’s bifractal structure.

For details, see [@yakubo2024random].

:::

