---
layout: default
permalink: /projects/triadic-nets
title: "Triadic Interactions"
description: "Oct 2022 --- Sep 2023"
year: 2023
bibliography:
  - reference.bib
---

Triadic interactions are higher-order, three-body interactions in which a node modulates edge between two other nodes.
Such interactions are reported in various real-world systems;
for example,  glia cells in the brain regulate synaptic connectivity between two neurons, either inhibiting or exciting synaptic signaling.
To model such interactions, we defined triadic interactions on network $G=(V,E)$ as an interaction between a node $i \in V$ and an edge $\ell \in E$ encoded by incidence matrix $\mathbf{K} \in \{-1, 0, 1\}^{|E| \times |V|}$ with entries
\begin{align}
  K_{\ell i} = \begin{cases}
    -1 & \text{if node $i$ inhibits edge $\ell$}, \\
    1 & \text{if node $i$ excites edge $\ell$}, \\
    0 & \text{otherwise}.
  \end{cases}
\end{align}
Signed triadic interactions turn percolation processes into dynamical ones, with phenomena such as a period doubling and chaos [[@sun2023dynamic], [@sun2024higher], [@millan2024triadic]], and dynamical implications of triadic interactions remain an important but open question. 

::: {.callout-note title="Langevin dynamics on networks with triadic interactions"}

To investigate how triadic interactions affect dynamics, we studied Langevin dynamics on networks incorporating triadic interactions
\begin{align}
  d\mathbf{X} = - (\mathbf{L}^{\textrm{(T)}} + \alpha \mathbf{I}) \mathbf{X} dt + \mathbf{\Gamma} d\mathbf{W}_{t}
\end{align}
where $d\mathbf{W}_{t}$ is the $|V|$-dimensional Wiener process and $\mathbf{L}^{\textrm{(T)}}$ is the triadic Laplacian 
\begin{align}
  L_{ij}^{\textrm{(T)}} (\mathbf{X}) &= \left(\sum_{k} J_{i k} (\mathbf{X}) \right) \delta_{ij} - J_{ij} (\mathbf{X})\\
  J_{ij}(\mathbf{X}; \hat{T}) &= w_{-} + (w_{+} - w_{-}) \theta\left(\sum_{k} K_{[i,j] k} X_{k} - \hat{T} \right)
\end{align}
that coevolves with $\mathbf{X}$. 
Excitation and inhibitation of triadic interactions are triggered when the states of triadically incident nodes collectively exceed a threshold $\hat{T}$.
Our results show that triadic interactions in the model are observable in conditional correlations and conditional mutual information among the three participating nodes, revealing both the strength and direction of the triadic interactions.

We applied this framework as a null model to identify potential triadic interactions in gene regulatory networks.

For details, see [@niedostatek2025mining].

:::