name: Publish Website

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

on:
  repository_dispatch:
    types: [deploy-docs]
  workflow_dispatch:
  push:
    branches: main

jobs:
  quarto:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
  
      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Render Website
        run: quarto render

      # Add additional assets to the _site directory before upload
      - name: Copy extra assets
        run: |
          mkdir -p _site/assets
          cp -r assets/* _site/assets/ 

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
